server {
    listen 80 default_server;
    server_name _;

    # Next.js standalone mode output includes .next/static/
    # Let Nginx serve these static files directly for better performance,
    # falling back to proxy if not found.
      
    location /_next/static/ {
        alias /opt/opc-recruitment-system/src/frontend/standalone/.next/static/;
        expires max;    
        access_log off;
    }

    
    
    
    
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    
    
    

    
    
    
    
    
    
    
    
    
    
    
}
